### ISSUE TITLE
Auto re-link packages

### ISSUE THREAD

**Issue by Whazor** [DomT4/homebrew-autoupdate#41] opened 2021-03-22 08:48 UTC
I had an issue when starting node.js, when starting the library was not loaded. I had to: `brew unlink node && brew link node`.

Would it be possible to automate re-linking?

**Comment by DomT4** [comment] 2021-03-26 17:51
It should be done already by Homebrew. This tool doesn't actually touch anything the `brew` tool does itself, it just passes the `update` or `upgrade` command (whichever ones the user requested at launch) onto `brew` at specified time intervals and retains the logs locally.

I suspect you might have had an issue with `node` that happened _during_ the upgrade but wasn't caused by this tool. You should be able to check:
```
cat ~/Library/Logs/com.github.domt4.homebrew-autoupdate/com.github.domt4.homebrew-autoupdate.out
```

**Comment by DomT4** [comment] 2021-04-03 15:30
Closing as resolved but feel free to get back to me if you think the issue is related to this tap/tool specifically.

**Closed by DomT4** 2021-04-03 15:30 UTC
Labels: question, replied
